# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/design_1_tri_mode_ethernet_mac_0_0.xci
# IP: The module: 'design_1_tri_mode_ethernet_mac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/design_1_tri_mode_ethernet_mac_0_0.xci
# IP: The module: 'design_1_tri_mode_ethernet_mac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VipinSop_2018/testMyGPIO/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_tri_mode_ethernet_mac_0_0/synth/design_1_tri_mode_ethernet_mac_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tri_mode_ethernet_mac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
