set_property PACKAGE_PIN V15 [get_ports {RMII_PHY_M_0_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_0_txd[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_0_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_external_0_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_external_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_0_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_0_rxd[0]}]
set_property PACKAGE_PIN Y17 [get_ports {RMII_PHY_M_0_txd[0]}]
set_property PACKAGE_PIN W16 [get_ports {RMII_PHY_M_0_rxd[0]}]
set_property PACKAGE_PIN T17 [get_ports {RMII_PHY_M_0_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports RMII_PHY_M_0_crs_dv]
set_property IOSTANDARD LVCMOS33 [get_ports RMII_PHY_M_0_tx_en]
set_property PACKAGE_PIN V12 [get_ports RMII_PHY_M_0_tx_en]
set_property PACKAGE_PIN H15 [get_ports mdio_external_0_io]
set_property PACKAGE_PIN V13 [get_ports mdio_external_0_mdc]
set_property PACKAGE_PIN U17 [get_ports RMII_PHY_M_0_crs_dv]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {RMII_PHY_M_0_rxd_IBUF[0]} {RMII_PHY_M_0_rxd_IBUF[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {RMII_PHY_M_0_txd_OBUF[0]} {RMII_PHY_M_0_txd_OBUF[1]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[0]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[1]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[2]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[3]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[4]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[5]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[6]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[7]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[8]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[9]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[10]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[11]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[12]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[13]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[14]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_1[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/conf/gen_mdio.int_ma_rx_data_reg[15]_0[0]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 27 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[0]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[1]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[2]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[3]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[4]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[5]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[6]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[7]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[8]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[9]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[10]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[11]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[12]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[13]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[14]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[15]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[17]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[18]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[19]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[20]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[21]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[22]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[23]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[24]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[25]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[26]} {design_1_i/tri_mode_ethernet_mac_0/inst/design_1_tri_mode_ethernet_mac_0_0_core/man_block.managen/mdio_enabled.phy/mdio_data[27]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
